mysql:
   host: localhost
   port: 3306
   database: landmanager
   user: mc
   password:

protections:
   restricted_worlds_mode: whitelist
   restricted_worlds_list: []
   blocks:
      chest:
         auto_protect: true

land_claims:
   restricted_worlds_mode: whitelist
   restricted_worlds_list: []
   default_claim_limit_per_player: 3

random_tp:
   default_radius: 1000
   worlds:
      melonWorld: 500
   pass_limit: 100
