name: LandManager
main: co.neweden.LandManager.Main
author: AaronMcH
description: Manages land claims, and block and entity protections
website: https://neweden.co/
version: 0.1-SNAPSHOT
depend: [MenuGUI]
commands:
   claim:
      description: Claim the chunk the player is standing in, either as a new claim or for an existing one
      permission: landmanager.claim
   newclaim:
      description: Claim the chunk the player is standing in as a new claim, regardless of claims around it, optionally specify the name to give to this new claim, spaces are allowed
      permission: landmanager.claim
      usage: /newclaim [NAME]
   unclaim:
      description: Un-claim the chunk the player is standing in, if no other chunks exist in the Land Claim it will be deleted
      permission: landmanager.unclaim
   linfo:
      description: Get information about the Land Claim the player is standing in
      permission: landmanager.linfo
   ltransfer:
      description: Transfer ownership of the Land Claim the player is standing in to another player
      permission: landmanager.ltransfer
      usage: /ltransfer [PLAYER_NAME]
   ladd:
      description: Add another player to the access list for the Land the player is standing in
      permission: landmanager.ladd
      usage: /ladd [PLAYER_NAME] [LEVEL]
   lremove:
      description: Add another player from the access list for the Land the player is standing in
      permission: landmanager.lremove
      usage: /ladd [PLAYER_NAME]
permissions:
   landmanager.*:
      description: Gives all LandManager permission nodes
      default: op
      children:
         landmanager.land.moderator: true
   landmanager.land:
      description: Gives player permissions to claim and use Land
      children:
         landmanager.claim: true
         landmanager.unclaim: true
         landmanager.linfo: true
         landmanager.ltransfer: true
         landmanager.ladd: true
         landmanager.lremove: true
   landmanager.land.moderator:
      description: Gives moderator permissions to manage land
      children:
         landmanager.land: true
         landmanager.unclaim.any: true
         landmanager.enterany: true
         landmanager.linfo.any: true
         landmanager.ltransfer.any: true
         landmanager.ladd.any: true
         landmanager.lremove.any: true
   landmanager.claim:
      description: Permission to use /claim and /newclaim commands
   landmanager.unclaim:
      description: Permission to use /unclaim command
   landmanager.unclaim.any:
      description: Permission to use /unclaim command on any chunk regardless of ACL Level
   landmanager.enterany:
      description: Permission to enter any land claim regardless of ACL Level
   landmanager.linfo:
      description: Permission to use /linfo command
   landmanager.linfo.any:
      description: Permission to use /linfo command regardless of ACL Level
   landmanager.ltransfer:
      description: Permission to use /linfo command
   landmanager.ltransfer.any:
      description: Permission to use /ltransfer command regardless of ACL Level
   landmanager.ladd:
      description: Permission to use /ladd command
   landmanager.ladd.any:
      description: Permission to use /ladd command regardless of ACL Level
   landmanager.lremove:
      description: Permission to use /lremove command
   landmanager.lremove.any:
      description: Permission to use /lremove command regardless of ACL Level
