name: LandManager
main: co.neweden.LandManager.Main
author: AaronMcH
description: Manages land claims, and block and entity protections
website: https://neweden.co/
version: 0.1-SNAPSHOT
depend: [MenuGUI]
commands:
   landmanager:
      description: Administrative command to manage LandManager
      permission: landmanager.admin
   ppersist:
      description: Toggle persist mode for protection commands
      permission: landmanager.ppersist
   pprotect:
      description: Create a new protection
      permission: landmanager.pprotect
      aliases: lock
   unlock:
      description: Remove a protection
      permission: landmanager.unlock
   pinfo:
      description: Get information about a Protection
      permission: landmanager.pinfo
   ptransfer:
      description: Transfer ownership of a Protection to another player
      permission: landmanager.ptransfer
      usage: /ptransfer [PLAYER_NAME]
   paccess:
      description: Modify the access list for a Protection
      permission: landmanager.paccess
   ppublic:
      description: Make the Protection public so everyone can use it
      permission: landmanager.ppublic
      usage: /ppublic [LEVEL]
   pprivate:
      description: Make the Protection private, resetting the ACL level for everyone back to the default
      permission: landmanager.pprivate
   claim:
      description: Claim the chunk the player is standing in, either as a new claim or for an existing one
      permission: landmanager.claim
   newclaim:
      description: Claim the chunk the player is standing in as a new claim, regardless of claims around it, optionally specify the name to give to this new claim, spaces are allowed
      permission: landmanager.claim
      usage: /newclaim [NAME]
   unclaim:
      description: Un-claim the chunk the player is standing in, if no other chunks exist in the Land Claim it will be deleted
      permission: landmanager.unclaim
   linfo:
      description: Get information about the Land Claim the player is standing in
      permission: landmanager.linfo
   ltransfer:
      description: Transfer ownership of the Land Claim the player is standing in to another player
      permission: landmanager.ltransfer
      usage: /ltransfer [PLAYER_NAME]
   laccess:
      description: Modify the access list for the Land the player is standing in
      permission: landmanager.laccess
      usage: /ladd [PLAYER_NAME] [LEVEL]
   lpublic:
      description: Make the Land public so everyone can use it
      permission: landmanager.lpublic
      usage: /lpublic [LEVEL]
   lprivate:
      description: Make the Land private, resetting the ACL level for everyone back to the default
      permission: landmanager.lprivate
   lrename:
      description: Change the name that shows up in /myland for this land, name can have spaces
      permission: landmanager.lrename
   lseticon:
      description: Change the icon that shows up in /myland for this land, can be any Minecraft Material
      permission: landmanager.lseticon
   lsethomeblock:
      description: Change the location that players are teleported to when teleporting to this Land Claim
      permission: landmanager.lsethomeblock
   listland:
      description: Displays Land that the current player or the given player has access to
      permission: landmanager.listland
      usage: /listland [PLAYER_NAME]
      aliases: myland
   rtp:
      description: Teleports you to a random location
      permission: landmanager.rtp
      aliases: [randomtp, random, wild, wilderness]
permissions:
   landmanager.*:
      description: Gives all LandManager permission nodes
      default: op
      children:
         landmanager.land.moderator: true
         landmanager.protections.moderator: true
         landmanager.admin: true
   landmanager.admin:
      description: Permission to use /landmanager command
   landmanager.rtp:
      description: Permission to use /rtp command
   landmanager.protections:
      description: Gives player permissions to protect things
      children:
         landmanager.ppersist: true
         landmanager.pprotect: true
         landmanager.unlock: true
         landmanager.pinfo: true
         landmanager.ptransfer: true
         landmanager.paccess: true
         landmanager.ppublic: true
         landmanager.pprivate: true
   landmanager.protections.moderator:
      description: Gives moderator permissions to manage protections
      children:
         landmanager.unlock.any: true
         landmanager.protection.interactany: true
         landmanager.pinfo.any: true
         landmanager.ptransfer.any: true
         landmanager.paccess.any: true
         landmanager.ppublic.any: true
         landmanager.pprivate.any: true
   landmanager.land:
      description: Gives player permissions to claim and use Land
      children:
         landmanager.claim: true
         landmanager.unclaim: true
         landmanager.linfo: true
         landmanager.ltransfer: true
         landmanager.laccess: true
         landmanager.lpublic: true
         landmanager.lprivate: true
         landmanager.lrename: true
         landmanager.lseticon: true
         landmanager.lsethomeblock: true
         landmanager.listland: true
   landmanager.land.moderator:
      description: Gives moderator permissions to manage land
      children:
         landmanager.land: true
         landmanager.unclaim.any: true
         landmanager.land.enterany: true
         landmanager.land.interactany: true
         landmanager.linfo.any: true
         landmanager.ltransfer.any: true
         landmanager.laccess.any: true
         landmanager.lpublic.any: true
         landmanager.lprivate.any: true
         landmanager.lrename.any: true
         landmanager.lseticon.any: true
         landmanager.lsethomeblock.any: true
         landmanager.listland.others: true
   landmanager.ppersist:
      description: Permission to use /ppersist command
   landmanager.pprotect:
      description: Permission to use /pprotect and /lock command
   landmanager.unlock:
      description: Permission to use /unlock command
   landmanager.unlock.any:
      description: Permission to use /unlock command on any protection regardless of ACL Level
   landmanager.protection.interactany:
      description: Permission to interact with any Protection regardless of ACL Level
   landmanager.pinfo:
      description: Permission to use /pinfo command
   landmanager.pinfo.any:
      description: Permission to use /pinfo command on any protection regardless of ACL Level
   landmanager.ptransfer:
      description: Permission to use /ptransfer command
   landmanager.ptransfer.any:
      description: Permission to use /ptransfer command on any protection regardless of ACL Level
   landmanager.paccess:
      description: Permission to use /paccess command
   landmanager.paccess.any:
      description: Permission to use /paccess command on any protection regardless of ACL Level
   landmanager.ppublic:
      description: Permission to use /ppublic command
   landmanager.ppublic.any:
      description: Permission to use /ppublic command on any protection regardless of ACL Level
   landmanager.pprivate:
      description: Permission to use /pprivate command
   landmanager.pprivate.any:
      description: Permission to use /pprivate command on any protection regardless of ACL Level
   landmanager.claim:
      description: Permission to use /claim and /newclaim commands
   landmanager.claimlimit.unlimited:
      description: No limit on number of Land Claims, replace "unlimited" with a number to assign that limit to the player
   landmanager.unclaim:
      description: Permission to use /unclaim command
   landmanager.unclaim.any:
      description: Permission to use /unclaim command on any chunk regardless of ACL Level
   landmanager.land.enterany:
      description: Permission to enter any land claim regardless of ACL Level
   landmanager.land.interactany:
      description: Permission to interact with any land claim regardless of ACL Level
   landmanager.linfo:
      description: Permission to use /linfo command
   landmanager.linfo.any:
      description: Permission to use /linfo command regardless of ACL Level
   landmanager.ltransfer:
      description: Permission to use /linfo command
   landmanager.ltransfer.any:
      description: Permission to use /ltransfer command regardless of ACL Level
   landmanager.laccess:
      description: Permission to use /laccess command
   landmanager.laccess.any:
      description: Permission to use /laccess command regardless of ACL Level
   landmanager.lremove.any:
      description: Permission to use /lremove command regardless of ACL Level
   landmanager.lpublic:
      description: Permission to use /lpublic command
   landmanager.lpublic.any:
      description: Permission to use /lpublic command regardless of ACL Level
   landmanager.lprivate:
      description: Permission to use /lprivate command
   landmanager.lprivate.any:
      description: Permission to use /lprivate command regardless of ACL Level
   landmanager.lrename:
      description: Permission to use /lrename command
   landmanager.lrename.any:
      description: Permission to use /lrename command regardless of ACL Level
   landmanager.lseticon:
      description: Permission to use /lseticon command
   landmanager.lseticon.any:
      description: Permission to use /lseticon command regardless of ACL Level
   landmanager.lsethomeblock:
      description: Permission to use /lsethomeblock command
   landmanager.lsethomeblock.any:
      description: Permission to use /lsethomeblock command regardless of ACL Level
   landmanager.listland:
      description: Permission to use /myland and /listland command
   landmanager.listland.others:
      description: Permission to use /listland command to view other players Land Lists
