name: LandManager
main: co.neweden.LandManager.Main
author: AaronMcH
description: Manages land claims, and block and entity protections
website: https://neweden.co/
version: 0.1-SNAPSHOT
depend: [MenuGUI]
commands:
   claim:
      description: Claim the chunk the player is standing in, either as a new claim or for an existing one
      permission: landmanager.claim
   newclaim:
      description: Claim the chunk the player is standing in as a new claim, regardless of claims around it, optionally specify the name to give to this new claim, spaces are allowed
      permission: landmanager.claim
      usage: /newclaim [NAME]
   unclaim:
      description: Un-claim the chunk the player is standing in, if no other chunks exist in the Land Claim it will be deleted
      permission: landmanager.unclaim
   linfo:
      description: Get information about the Land Claim the player is standing in
      permission: landmanager.linfo
   ltransfer:
      description: Transfer ownership of the Land Claim the player is standing in to another player
      permission: landmanager.ltransfer
      usage: /ltransfer [PLAYER_NAME]
   ladd:
      description: Add another player to the access list for the Land the player is standing in
      permission: landmanager.ladd
      usage: /ladd [PLAYER_NAME] [LEVEL]
   lremove:
      description: Add another player from the access list for the Land the player is standing in
      permission: landmanager.lremove
      usage: /ladd [PLAYER_NAME]
   lpublic:
      description: Make the Land public so everyone can use it
      permission: landmanager.lpublic
      usage: /lpublic [LEVEL]
   lprivate:
      description: Make the Land private resetting the aCL level fro everyone back to thee default
      permission: landmanager.lprivate
   lrename:
      description: Change the name that shows up in /myland for this land, name can have spaces
      permission: landmanager.lrename
   lseticon:
      description: Change the icon that shows up in /myland for this land, can be any Minecraft Material
      permission: landmanager.lseticon
   listland:
      description: Displays Land that the current player or the given player has access to
      permission: landmanager.listland
      usage: /listland [PLAYER_NAME]
      aliases: myland
permissions:
   landmanager.*:
      description: Gives all LandManager permission nodes
      default: op
      children:
         landmanager.land.moderator: true
   landmanager.land:
      description: Gives player permissions to claim and use Land
      children:
         landmanager.claim: true
         landmanager.unclaim: true
         landmanager.linfo: true
         landmanager.ltransfer: true
         landmanager.ladd: true
         landmanager.lremove: true
         landmanager.lpublic: true
         landmanager.lprivate: true
         landmanager.lrename: true
         landmanager.lseticon: true
         landmanager.listland: true
   landmanager.land.moderator:
      description: Gives moderator permissions to manage land
      children:
         landmanager.land: true
         landmanager.unclaim.any: true
         landmanager.land.enterany: true
         landmanager.land.interactany: true
         landmanager.linfo.any: true
         landmanager.ltransfer.any: true
         landmanager.ladd.any: true
         landmanager.lremove.any: true
         landmanager.lpublic.any: true
         landmanager.lprivate.any: true
         landmanager.lrename.any: true
         landmanager.lseticon.any: true
         landmanager.listland.others: true
   landmanager.claim:
      description: Permission to use /claim and /newclaim commands
   landmanager.unclaim:
      description: Permission to use /unclaim command
   landmanager.unclaim.any:
      description: Permission to use /unclaim command on any chunk regardless of ACL Level
   landmanager.land.enterany:
      description: Permission to enter any land claim regardless of ACL Level
   landmanager.land.interactany:
      description: Permission to interact with any land claim regardless of ACL Level
   landmanager.linfo:
      description: Permission to use /linfo command
   landmanager.linfo.any:
      description: Permission to use /linfo command regardless of ACL Level
   landmanager.ltransfer:
      description: Permission to use /linfo command
   landmanager.ltransfer.any:
      description: Permission to use /ltransfer command regardless of ACL Level
   landmanager.ladd:
      description: Permission to use /ladd command
   landmanager.ladd.any:
      description: Permission to use /ladd command regardless of ACL Level
   landmanager.lremove:
      description: Permission to use /lremove command
   landmanager.lremove.any:
      description: Permission to use /lremove command regardless of ACL Level
   landmanager.lpublic:
      description: Permission to use /lpublic command
   landmanager.lpublic.any:
      description: Permission to use /lpublic command regardless of ACL Level
   landmanager.lprivate:
      description: Permission to use /lprivate command
   landmanager.lprivate.any:
      description: Permission to use /lprivate command regardless of ACL Level
   landmanager.lrename:
      description: Permission to use /lrename command
   landmanager.lrename.any:
      description: Permission to use /lrename command regardless of ACL Level
   landmanager.lseticon:
      description: Permission to use /lseticon command
   landmanager.lseticon.any:
      description: Permission to use /lseticon command regardless of ACL Level
   landmanager.listland:
      description: Permission to use /myland and /listland command
   landmanager.listland.others:
      description: Permission to use /listland command to view other players Land Lists
