name: LandManager
main: co.neweden.LandManager.Main
author: AaronMcH
description: Manages land claims, and block and entity protections
website: https://neweden.co/
version: 0.1-SNAPSHOT
depend: [MenuGUI]
commands:
   claim:
      description: Claim the chunk the player is standing in, either as a new claim or for an existing one
      permission: landmanager.claim
   linfo:
      description: Get information about the Land Claim the player is standing in
      permission: landmanager.linfo
permissions:
   landmanager.*:
      description: Gives all LandManager permission nodes
      default: op
      children:
         landmanager.land.moderator: true
   landmanager.land:
      description: Gives player permissions to claim and use Land
      children:
         landmanager.claim: true
         landmanager.linfo: true
   landmanager.land.moderator:
      description: Gives moderator permissions to manage land
      children:
         landmanager.land: true
         landmanager.enterany: true
         landmanager.linfo.any: true
   landmanager.claim:
      description: Permission to use /claim command
   landmanager.enterany:
      description: Permission to enter any land claim regardless of ACL Level
   landmanager.linfo:
      description: Permission to use /linfo command
   landmanager.linfo.any:
      description: Permission to use /linfo command regardless of ACL Level
